path: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/Stefan_Encriptacion
user: root
passw: quevedo2dam
driver: com.mysql.cj.jdbc.Driver

#ruta: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/CarlosMartinezPrados_Periodico
#user: root
#password: quevedo2dam

#--module-path  ${PATH_TO_FX} --add-modules javafx.controls,javafx.fxml