ruta: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/Stefan_Baloncesto?useSSL=false
user: root
password: quevedo2dam
driver: com.mysql.cj.jdbc.Driver

#--module-path  ${PATH_TO_FX} --add-modules javafx.controls,javafx.fxml