#path: jdbc:mysql://localhost:3306/rol_local?useSSL=false
#user: root
#passw: root
#driver: com.mysql.cj.jdbc.Driver

path: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/rol?useSSL=false
user: root
passw: quevedo2dam
driver: com.mysql.cj.jdbc.Driver